<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
{
    $banks = [

        // UG
            ['UG','Absa Bank Uganda Ltd','013847','013847','pivot'],
            ['UG','Bank of Baroda','020147','020147','pivot'],
            ['UG','Stanbic Bank Ltd','040147','040147','pivot'],
            ['UG','DFCU Bank','050147','050147','pivot'],
            ['UG','Tropical Bank','060147','060147','pivot'],
            ['UG','Stanchart Bank','080147','080147','pivot'],
            ['UG','I & M Bank Uganda Ltd','110147','110147','pivot'],
            ['UG','Bank Of Africa','130447','130447','pivot'],
            ['UG','Centenary Bank','163747','163747','pivot'],
            ['UG','Cairo Bank Uganda','180147','180147','pivot'],
            ['UG','Diamond Trust Bank','190147','190147','pivot'],
            ['UG','Housing Finance Bank','230147','230147','pivot'],
            ['UG','Kenya Commercial Bank','252947','252947','pivot'],
            ['UG','United Bank for Africal','260147','260147','pivot'],
            ['UG','Guaranty Trust Bank','270147','270147','pivot'],
            ['UG','Ecobank','290147','290147','pivot'],
            ['UG','Equity Bank Uganda','300147','300147','pivot'],
            ['UG','ABC Bank','310147','310147','pivot'],
            ['UG','EXIM Bank','320147','320147','pivot'],
            ['UG','NCBA Bank','360147','360147','pivot'],
            ['UG','Finance Trust Bank','410147','410147','pivot'],
            ['UG','Uganda Development Bank','420147','420147','pivot'],
            ['UG','Post Bank Uganda','560147','560147','pivot'],
            ['UG','Bank of Indian','600147','600147','pivot'],
            ['UG','Opportunity Bank','610147','610147','pivot'],
            ['UG','UGAFODE MFI','730147','730147','pivot'],

    ['NG','VISA MICROFINANCE BANK','090139',null, 'payaza'],
    ['NG','VT NETWORKS','100012',null, 'payaza'],
    ['NG','WETLAND MICROFINANCE BANK','090120',null, 'payaza'],
    ['NG','XSLNCE MICROFINANCE BANK','090124',null, 'payaza'],
    ['NG','YCT MICROFINANCE BANK','090466',null, 'payaza'],
    ['NG','YES MICROFINANCE BANK','090142',null, 'payaza'],
    ['NG','YOBE MICROFINANCE BANK','090252',null, 'payaza'],
    ['NG','ZENITH EASY WALLET','100034',null, 'payaza'],
    ['NG','ZINTERNET - KONGAPAY','100025',null, 'payaza'],
     ['NG','ASO SAVINGS','090001','401', 'payaza'],
    ['NG','HACKMAN MICROFINANCE BANK','090147','51251', 'payaza'],
    ['NG','HASAL MICROFINANCE BANK','090121','50383', 'payaza'],
    ['NG','CITI BANK','000009','023', 'payaza'],
    ['NG','TAJ BANK','000026','302', 'payaza'],
    ['NG','BOWEN MICROFINANCE BANK','090148','50931', 'payaza'],
    ['NG','EKONDO MICROFINANCE BANK','090097','562', 'payaza'],
    ['NG','SUNTRUST BANK','000022','100', 'payaza'],
    ['NG','CEMCS MICROFINANCE BANK','090154','50823', 'payaza'],
    ['NG','PARKWAY-READYCASH','100003','311','payaza'],
    ['NG','LAGOS BUILDING AND INVESTMENT COMPANY','070012','90052', 'payaza'],
    ['NG','IBILE MICROFINANCE BANK','090118','51244', 'payaza'],
    ['NG','TCF MICROFINANCE BANK','090115','51211', 'payaza'],
    ['NG','INFINITY MICROFINANCE BANK','090157','50457', 'payaza'],
    ['NG','TITAN TRUST BANK','000025','102', 'payaza'],
    ['NG','UNITY BANK','000011','215', 'payaza'],
    ['NG','FIRST BANK OF NIGERIA','000016',null, 'payaza'],
    ['NG','ABBEY MORTGAGE BANK','070010','801', 'payaza'],
    ['NG','RAND MERCHANT BANK','000024','502', 'payaza'],
    ['NG','PETRA MICROFINANCE BANK','090165','50746', 'payaza'],
    ['NG','HERITAGE BANK','000020','030', 'payaza'],
    ['NG','CORONATION MERCHANT BANK','060001','559', 'payaza'],
    ['NG','JAIZ BANK','000006','301', 'payaza'],
    ['NG','PALMPAY','100033',null, 'payaza'],
    ['NG','ZIKORA MICROFINANCE BANK','090504',null, 'payaza'],
    ['NG','SOLID ALLIANZE MICROFINANCE BANK','090506',null, 'payaza'],
    ['NG','SMARTCASH PAYMENT SERVICE BANK','120004',null, 'payaza'],
    ['NG','HOMEBASE MORTGAGE BANK','0070024',null, 'payaza'],
    ['NG','KEGOW(CHAMSMOBILE)','100036',null, 'payaza'],
    ['NG','MOMO PAYMENT SERVICE BANK','120003',null, 'payaza'],
    ['NG','FEWCHORE FINANCE COMPANY LIMITED','050002',null, 'payaza'],
    ['NG','ABULESORO MICROFINANCE BANK','090545',null, 'payaza'],
    ['NG','CATLAND MICROFINANCE BANK','90498',null, 'payaza'],
    ['NG','CONFIDENCE MICROFINANCE BANK','090530',null, 'payaza'],
    ['NG','CRESCENT MICROFINANCE BANK','90526',null, 'payaza'],
    ['NG','EXCELLENT MICROFINANCE BANK','090541',null, 'payaza'],
    ['NG','FORESIGHT MICROFINANCE BANK','90521',null, 'payaza'],
    ['NG','IBOM FADAMA MICROFINANCE BANK','90519',null, 'payaza'],
    ['NG','ECOBANK','000010',null, 'payaza'],
    ['NG','POLARIS BANK','000008','076', 'payaza'],
    ['NG','RUBIES MICROFINANCE BANK','090175','125', 'payaza'],
    ['NG','SPARKLE','090325','51310', 'payaza'],
    ['NG','UNITED BANK FOR AFRICA','000004','033', 'payaza'],
    ['NG','STANBIC IBTC BANK','000012','221', 'payaza'],
    ['NG','ACCESS BANK','000014',null, 'payaza'],
    ['NG','FIDELITY BANK','000007',null, 'payaza'],
    ['NG','UNION BANK','000018','032', 'payaza'],
    ['NG','WEMA BANK','000017','035', 'payaza'],
    ['NG','CARBON','100026','565', 'payaza'],
    ['NG','IC GLOBAL MICROFINANCE BANK','90520',null, 'payaza'],
    ['NG','MERIDAN MFB','090275',null, 'payaza'],
    ['NG','Moneymaster PSB','120005',null, 'payaza'],
    ['NG','NIGERIA PRISONS MICROFINANCE BANK','90505',null, 'payaza'],
    ['NG','OKE-ARO OREDEGBE MFB','090565',null, 'payaza'],
    ['NG','RIMA GROWTH PATHWAY MICROFINANCE BANK','90515',null, 'payaza'],
    ['NG','ROCKSHIELD MICROFINANCE BANK','90547',null, 'payaza'],
    ['NG','SAGE GREY FINANCE LIMITED','50003',null, 'payaza'],
    ['NG','SEAP MICROFINANCE BANK','90513',null, 'payaza'],
    ['NG','SOLIDROCK MICROFINANCE BANK','90524',null, 'payaza'],
    ['NG','TANADI MFB (CRUST)','090560',null, 'payaza'],
    ['NG','TITAN-PAYSTACK','100039',null, 'payaza'],
    ['NG','UHURU MICROFINANCE BANK','90517',null, 'payaza'],
    ['NG','AMPERSAND MICROFINANCE BANK','090529',null, 'payaza'],
    ['NG','ALLY MICROFINANCE BANK','090548',null, 'payaza'],
    ['NG','ASPIRE MICROFINANCE BANK','090544',null, 'payaza'],
    ['NG','BALERA MICROFINANCE BANK','090563',null, 'payaza'],
    ['NG','BISHOPGATE MICROFINANCE BANK','090555',null, 'payaza'],
    ['NG','CEDAR MICROFINANCE BANK','090562',null, 'payaza'],
    ['NG','CONSISTENT TRUST MICROFINANCE BANK','090553',null, 'payaza'],
    ['NG','COUNTY FINANCE LIMITED','050001',null, 'payaza'],
    ['NG','GREEN ENERGY MICROFINANCE BANK','090550',null, 'payaza'],
    ['NG','HALALCREDIT MICROFINANCE BANK','090291',null, 'payaza'],
    ['NG','IJEBU-IFE MICROFINANCE BANK','090546',null, 'payaza'],
    ['NG','ILARO POLY MICROFINANCE BANK','090571',null, 'payaza'],
    ['NG','IWOAMA MICROFINANCE BANK','090543',null, 'payaza'],
    ['NG','KAYVEE MICROFINANCE BANK','090554',null, 'payaza'],
    ['NG','KC MICROFINANCE BANK','090549',null, 'payaza'],
    ['NG','LIFEGATE MICROFINANCE BANK','090557',null, 'payaza'],
    ['NG','OKUKU MICROFINANCE BANK','090566',null, 'payaza'],
    ['NG','OROKAM MICROFINANCE BANK','090567',null, 'payaza'],
    ['NG','OTUO MICROFINANCE BANK','090542',null, 'payaza'],
    ['NG','SHIELD MICROFINANCE BANK','090559',null, 'payaza'],
     ['NG','SHONGOM MICROFINANCE BANK','090558',null, 'payaza'],
    ['NG','SLS MICROFINANCE BANK','090449',null, 'payaza'],
    ['NG','SUPREME MICROFINANCE BANK','090564',null, 'payaza'],
    ['NG','TRIPLEA MICROFINANCE BANK','090525',null, 'payaza'],
    ['NG','UDA MICROFINANCE BANK','090403',null, 'payaza'],
    ['NG','VERDANT MICROFINANCE BANK','090474',null, 'payaza'],
    ['NG','BROADVIEW MICROFINANCE BANK','090568',null, 'payaza'],
    ['NG','FairMoney','090551',null, 'payaza'],
    ['NG','IYE OKIN MICROFINANCE BANK LTD','090337',null, 'payaza'],
    ['NG','OTECH MICROFINANCE BANK','090580',null, 'payaza'],
    ['NG','SAGE GREY FINANCE LIMITED','050003',null, 'payaza'],
    ['NG','MERCURY MICROFINANCE BANK','090589',null, 'payaza'],
    ['NG','MKOBO MICROFINANCE BANK','090455',null, 'payaza'],
    ['NG','SIGNATURE BANK','000034',null, 'payaza'],
    ['NG','AAA FINANCE AND INVESTMENT COMPANY LIMITED','050005',null, 'payaza'],
    ['NG','AKUCHUKWU MICROFINANCE BANK','090561',null, 'payaza'],
    ['NG','ENCO FINANCE COMPANY LTD','050012',null, 'payaza'],
    ['NG','GABSYN MICROFINANCE BANK','090591',null, 'payaza'],
    ['NG','OPTIMUS BANK','000036',null, 'payaza'],
    ['NG','ISLAND MICROFINANCE BANK','090584',null, 'payaza'],
    ['NG','TEKLA FACTORING AND FINANCE LIMITED','050007',null, 'payaza'],
    ['NG','AKPO MICROFINANCE BANK','090608',null, 'payaza'],
    ['NG','AMOYE MICROFINANCE BANK','090610',null, 'payaza'],
    ['NG','Stateside MFB','090583',null, 'payaza'],
    ['NG','DIGNITY FINANCE AND INVESTMENT LIMITED','050013',null, 'payaza'],
    ['NG','MEDEF MICROFINANCE BANK','090612',null, 'payaza'],
    ['NG','UMMAH MICROFINANCE BANK','090609',null, 'payaza'],
    ['NG','BRANCH INTERNATIONAL FINANCIAL SERVICES','050006',null, 'payaza'],
    ['NG','SHALOM MICROFINANCE BANK','090502',null, 'payaza'],
    ['NG','RAYYAN MICROFINANCE BANK','090616',null, 'payaza'],
    ['NG','FLOURISH MICROFINANCE BANK','090614',null, 'payaza'],
    ['NG','MAB ALLIANZ MICROFINANCE BANK','090623',null, 'payaza'],
    ['NG','AL-HAYAT MICROFINANCE BANK','090277',null, 'payaza'],
    ['NG','ALLWORKERS MICROFINANCE BANK','090131',null, 'payaza'],
    ['NG','ALPHA KAPITAL MICROFINANCE BANK','090169',null, 'payaza'],
    ['NG','AMAC MICROFINANCE BANK','090394',null, 'payaza'],
    ['NG','AMJU UNIQUE MICROFINANCE BANK','090180',null, 'payaza'],
    ['NG','AMML MICROFINANCE BANK','090116',null, 'payaza'],
    ['NG','APEKS MICROFINANCE BANK','090143',null, 'payaza'],
    ['NG','APPLE MICROFINANCE BANK','090376',null, 'payaza'],
    ['NG','ARISE MICROFINANCE BANK','090282',null, 'payaza'],
    ['NG','COVENANT MFB','070006',null, 'payaza'],
    ['NG','CREDIT AFRIQUE MICROFINANCE BANK','090159',null, 'payaza'],
    ['NG','CYBERSPACE LIMITED','110014',null, 'payaza'],
    ['NG','DAVODANI  MICROFINANCE BANK','090391',null, 'payaza'],
    ['NG','DAYLIGHT MICROFINANCE BANK','090167',null, 'payaza'],
    ['NG','EAGLE FLIGHT MICROFINANCE BANK','090294',null, 'payaza'],
    ['NG','EARTHOLEUM','100021',null, 'payaza'],
    ['NG','ASSETMATRIX MICROFINANCE BANK','090287',null, 'payaza'],
    ['NG','ASTRAPOLARIS MICROFINANCE BANK','090172',null, 'payaza'],
    ['NG','AUCHI MICROFINANCE BANK','090264',null, 'payaza'],
    ['NG','BAINES CREDIT MICROFINANCE BANK','090188',null, 'payaza'],
    ['NG','BALOGUN GAMBARI MICROFINANCE BANK','090326',null, 'payaza'],
    ['NG','BAYERO UNIVERSITY MICROFINANCE BANK','090316',null, 'payaza'],
    ['NG','BC KASH MICROFINANCE BANK','090127',null, 'payaza'],
    ['NG','BIPC MICROFINANCE BANK','090336',null, 'payaza'],
    ['NG','BOCTRUST MICROFINANCE BANK LIMITED','090117',null, 'payaza'],
    ['NG','BORGU  MICROFINANCE BANK','090395',null, 'payaza'],
    ['NG','BOSAK MICROFINANCE BANK','090176',null, 'payaza'],
     ['NG','BRENT MORTGAGE BANK','070015',null, 'payaza'],
    ['NG','BRETHREN MICROFINANCE BANK','090293',null, 'payaza'],
    ['NG','BRIDGEWAY MICROFINANACE BANK','090393',null, 'payaza'],
    ['NG','BRIGHTWAY MICROFINANCE BANK','090308',null, 'payaza'],
    ['NG','BUSINESS SUPPORT MICROFINANCE BANK','090406',null, 'payaza'],
    ['NG','E-BARCS MICROFINANCE BANK','090156',null, 'payaza'],
    ['NG','ECOBANK XPRESS ACCOUNT','100008',null, 'payaza'],
    ['NG','ECOMOBILE','100030',null, 'payaza'],
    ['NG','EDFIN MICROFINANCE BANK','090310',null, 'payaza'],
    ['NG','EK-RELIABLE MICROFINANCE BANK','090389',null, 'payaza'],
    ['NG','EMERALD MICROFINANCE BANK','090273',null, 'payaza'],
    ['NG','EMPIRE TRUST MICROFINANCE BANK','090114',null, 'payaza'],
    ['NG','ENTERPRISE BANK','000019',null, 'payaza'],
    ['NG','ESAN MICROFINANCE BANK','090189',null, 'payaza'],
    ['NG','ESO-E MICROFINANCE BANK','090166',null, 'payaza'],
    ['NG','eTRANZACT','100006',null, 'payaza'],
    ['NG','EVANGEL MICROFINANCE BANK','090304',null, 'payaza'],
    ['NG','EVERGREEN MICROFINANCE BANK','090332',null, 'payaza'],
    ['NG','EYOWO','090328',null, 'payaza'],
    ['NG','FAST MICROFINANCE BANK','090179',null, 'payaza'],
    ['NG','FBNQUEST MERCHANT BANK','060002',null, 'payaza'],
    ['NG','FCMB MOBILE','100031',null, 'payaza'],
    ['NG','FCT MICROFINANCE BANK','090290',null, 'payaza'],
     ['NG','FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK','090398',null, 'payaza'],
    ['NG','FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK','090318',null, 'payaza'],
    ['NG','FEDETH MICROFINANCE BANK','090482',null, 'payaza'],
    ['NG','FEDPOLY NASARAWA MICROFINANCE BANK','090298',null, 'payaza'],
    ['NG','FETS','100001',null, 'payaza'],
    ['NG','FFS MICROFINANCE BANK','090153',null, 'payaza'],
    ['NG','FIDELITY MOBILE','100019',null, 'payaza'],
    ['NG','FIDFUND MICROFINANCE Bank','090126',null, 'payaza'],
    ['NG','FINATRUST MICROFINANCE BANK','090111',null, 'payaza'],
    ['NG','FINCA MICROFINANCE BANK','090400',null, 'payaza'],
    ['NG','FIRMUS MICROFINANCE BANK','090366',null, 'payaza'],
    ['NG','FIRST APPLE LIMITED','110004',null, 'payaza'],
    ['NG','FIRST GENERATION MORTGAGE BANK','070014',null, 'payaza'],
     ['NG','FIRST OPTION MICROFINANCE BANK','090285',null, 'payaza'],
    ['NG','FIRST ROYAL MICROFINANCE BANK','090164',null, 'payaza'],
    ['NG','FIRST TRUST MORTGAGE BANK PLC','090107',null, 'payaza'],
    ['NG','FIRSTMONIE WALLET','100014',null, 'payaza'],
    ['NG','ZENITH MOBILE','100018',null, 'payaza'],
    ['NG','FLUTTERWAVE TECHNOLOGY SOLUTIONS LIMITED','110002',null, 'payaza'],
    ['NG','FORTIS MICROFINANCE BANK','070002',null, 'payaza'],
    ['NG','FORTIS MOBILE','100016',null, 'payaza'],
    ['NG','FULLRANGE MICROFINANCE BANK','090145',null, 'payaza'],
    ['NG','FUTO MICROFINANCE BANK','090158',null, 'payaza'],
    ['NG','GASHUA MICROFINANCE BANK','090168',null, 'payaza'],
    ['NG','GATEWAY MORTGAGE BANK','070009',null, 'payaza'],
    ['NG','GIREI MICROFINANACE BANK','090186',null, 'payaza'],
    ['NG','GLORY MICROFINANCE BANK','090278',null, 'payaza'],
    ['NG','GMB MICROFINANCE BANK','090408',null, 'payaza'],
    ['NG','GOWANS MICROFINANCE BANK','090122',null, 'payaza'],
    ['NG','GREENBANK MICROFINANCE BANK','090178',null, 'payaza'],
    ['NG','GREENVILLE MICROFINANCE BANK','090269',null, 'payaza'],
    ['NG','GREENWICH MERCHANT BANK','060004',null, 'payaza'],
    ['NG','GROOMING MICROFINANCE BANK','090195',null, 'payaza'],
    ['NG','GTI MICROFINANCE BANK','090385',null, 'payaza'],
    ['NG','HAGGAI MORTGAGE BANK LIMITED','070017',null, 'payaza'],
    ['NG','HEADWAY MICROFINANCE BANK','090363',null, 'payaza'],
    ['NG','HEDONMARK','100017',null, 'payaza'],
    ['NG','HOPEPSB','120002',null, 'payaza'],
    ['NG','IKENNE MICROFINANCE BANK','090324',null, 'payaza'],
    ['NG','IKIRE MICROFINANCE BANK','090279',null, 'payaza'],
    ['NG','ILISAN MICROFINANCE BANK','090370',null, 'payaza'],
    ['NG','IMO STATE MICROFINANCE BANK','090258',null, 'payaza'],
    ['NG','IMPERIAL HOMES MORTGAGE BANK','100024',null, 'payaza'],
    ['NG','INFINITY TRUST MORTGAGE BANK','070016',null, 'payaza'],
    ['NG','INNOVECTIVES KESH','100029',null, 'payaza'],
     ['NG','INTELLIFIN','100027',null, 'payaza'],
    ['NG','INTERLAND MICROFINANCE BANK','090386',null, 'payaza'],
    ['NG','INTERSWITCH LIMITED','110003',null, 'payaza'],
    ['NG','IRL MICROFINANCE BANK','090149',null, 'payaza'],
    ['NG','ISALEOYO MICROFINANCE BANK','090377',null, 'payaza'],
    ['NG','JUBILEE LIFE','090003',null, 'payaza'],
    ['NG','KADPOLY MICROFINANCE BANK','090320',null, 'payaza'],
    ['NG','KCMB MICROFINANCE BANK','090191',null, 'payaza'],
    ['NG','KONTAGORA MICROFINANCE BANK','090299',null, 'payaza'],
    ['NG','KREDI MONEY MICROFINANCE BANK','090380',null, 'payaza'],
    ['NG','LAPO MICROFINANCE BANK','090177',null, 'payaza'],
    ['NG','LAVENDER MICROFINANCE BANK','090271',null, 'payaza'],
    ['NG','LEGEND MICROFINANCE BANK','090372',null, 'payaza'],
    ['NG','LINKS MICROFINANCE BANK','090435',null, 'payaza'],
    ['NG','LIVINGTRUST MORTGAGE BANK PLC','070007',null, 'payaza'],
      ['NG','LOVONUS MICROFINANCE BANK','090265',null, 'payaza'],
    ['NG','MAINLAND MICROFINANCE BANK','090323',null, 'payaza'],
    ['NG','MAINSTREET MICROFINANCE BANK','090171',null, 'payaza'],
    ['NG','FSDH','400001','501', 'payaza'],
    ['NG','MALACHY MICROFINANCE BANK','090174',null, 'payaza'],
    ['NG','MANNY MICROFINANCE BANK','090383',null, 'payaza'],
    ['NG','MARITIME MICROFINANCE BANK','090410',null, 'payaza'],
    ['NG','MAYFAIR MICROFINANCE BANK','090321',null, 'payaza'],
    ['NG','MAYFRESH MORTGAGE BANK','070019',null, 'payaza'],
    ['NG','MEGAPRAISE MICROFINANCE BANK','090280',null, 'payaza'],
    ['NG','MICROCRED MICROFINANCE BANK','090136',null, 'payaza'],
    ['NG','MICROVIS MICROFINANCE BANK','090113',null, 'payaza'],
    ['NG','MIDLAND MICROFINANCE BANK','090192',null, 'payaza'],
    ['NG','MINT-FINEX MFB','090281',null, 'payaza'],
    ['NG','MKUDI','100011',null, 'payaza'],
    ['NG','MOLUSI MICROFINANCE BANK','090362',null, 'payaza'],
    ['NG','MONEY BOX','100020',null, 'payaza'],
    ['NG','MONEY TRUST MICROFINANCE BANK','090129',null, 'payaza'],
    ['NG','MOZFIN MICROFINANCE BANK','090392',null, 'payaza'],
    ['NG','MUTUAL BENEFITS MICROFINANCE BANK','090190',null, 'payaza'],
     ['NG','MUTUAL TRUST MICROFINANCE BANK','090151',null, 'payaza'],
    ['NG','NAGARTA MICROFINANCE BANK','090152',null, 'payaza'],
    ['NG','NDIORAH MICROFINANCE BANK','090128',null, 'payaza'],
    ['NG','NEPTUNE MICROFINANCE BANK','090329',null, 'payaza'],
    ['NG','NEW DAWN MICROFINANCE BANK','090205',null, 'payaza'],
    ['NG','NEW GOLDEN PASTURES MICROFINANCE BANK','090378',null, 'payaza'],
    ['NG','NEW PRUDENTIAL BANK','090108',null, 'payaza'],
    ['NG','NIGERIAN NAVY MICROFINANCE BANK','090263',null, 'payaza'],
    ['NG','NIP VIRTUAL BANK','999999',null, 'payaza'],
    ['NG','NIRSAL NATIONAL MICROFINANCE BANK','090194',null, 'payaza'],
     ['NG','NNEW WOMEN MICROFINANCE BANK','090283',null, 'payaza'],
    ['NG','NOVA MERCHANT BANK','060003',null, 'payaza'],
    ['NG','NOWNOW DIGITAL SYSTEMS LIMITED','100032',null, 'payaza'],
    ['NG','NPF MICROFINANCE BANK','070001',null, 'payaza'],
    ['NG','NUTURE MICROFINANCE BANK','090364',null, 'payaza'],
    ['NG','NWANNEGADI MICROFINANCE BANK','090399',null, 'payaza'],
    ['NG','OCHE MICROFINANCE BANK','090333',null, 'payaza'],
    ['NG','OHAFIA MICROFINANCE BANK','090119',null, 'payaza'],
    ['NG','OKPOGA MICROFINANCE BANK','090161',null, 'payaza'],
    ['NG','OLABISI ONABANJO UNIVERSITY MICROFINANCE','090272',null, 'payaza'],
    ['NG','OLOWOLAGBA MICROFINANCE BANK','090404',null, 'payaza'],
    ['NG','OMIYE MICROFINANCE BANK','090295',null, 'payaza'],
    ['NG','OSCOTECH MICROFINANCE BANK','090396',null, 'payaza'],
    ['NG','PAGE MFBank','070008',null, 'payaza'],
    ['NG','PARALLEX BANK','000030',null, 'payaza'],
    ['NG','PATRICKGOLD MICROFINANCE BANK','090317',null, 'payaza'],
    ['NG','PAYATTITUDE ONLINE','110001',null, 'payaza'],
    ['NG','PEACE MICROFINANCE BANK','090402',null, 'payaza'],
    ['NG','PECANTRUST MICROFINANCE BANK','090137',null, 'payaza'],
    ['NG','PENNYWISE MICROFINANCE BANK','090196',null, 'payaza'],
    ['NG','PERSONAL TRUST MICROFINANCE BANK','090135',null, 'payaza'],
    ['NG','PETRA MICROFINANCE BANK','90165',null, 'payaza'],
    ['NG','PILLAR MICROFINANCE BANK','090289',null, 'payaza'],
    ['NG','PLATINUM MORTGAGE BANK','070013',null, 'payaza'],
    ['NG','POLYUNWANA MICROFINANCE BANK','090296',null, 'payaza'],
    ['NG','PRESTIGE MICROFINANCE BANK','090274',null, 'payaza'],
    ['NG','PURPLEMONEY MICROFINANCE BANK','090303',null, 'payaza'],
    ['NG','QUICKFUND MICROFINANCE BANK','090261',null, 'payaza'],
    ['NG','REFUGE MORTGAGE BANK','070011',null, 'payaza'],
    ['NG','REGENT MICROFINANCE BANK','090125',null, 'payaza'],
    ['NG','RELIANCE MICROFINANCE BANK','090173',null, 'payaza'],
    ['NG','RENMONEY MICROFINANCE BANK','090198',null, 'payaza'],
    ['NG','REPHIDIM MICROFINANCE BANK','090322',null, 'payaza'],
     ['NG','RICHWAY MICROFINANCE BANK','090132',null, 'payaza'],
    ['NG','RIGO MICROFINANCE BANK','090433',null, 'payaza'],
    ['NG','ROYAL EXCHANGE MICROFINANCE BANK','090138',null, 'payaza'],
    ['NG','SAFE HAVEN MICROFINANCE BANK','090286',null, 'payaza'],
    ['NG','SAFEGATE MICROFINANCE BANK','090485',null, 'payaza'],
    ['NG','SAFETRUST','090006',null, 'payaza'],
    ['NG','SAGAMU MICROFINANCE BANK','090140',null, 'payaza'],
    ['NG','SEED CAPITAL MICROFINANCE BANK','090112',null, 'payaza'],
    ['NG','SEEDVEST MICROFINANCE BANK','090369',null, 'payaza'],
    ['NG','SHERPERD TRUST MICROFINANCE BANK','090401',null, 'payaza'],
    ['NG','SPECTRUM MICROFINANCE BANK','090436',null, 'payaza'],
    ['NG','STANBIC IBTC @Ease WALLET','100007',null, 'payaza'],
      ['NG','STANFORD MICROFINANCE BANK','090162',null, 'payaza'],
    ['NG','STELLAS MICROFINANCE BANK','090262',null, 'payaza'],
    ['NG','SULSPAP MICROFINANCE BANK','090305',null, 'payaza'],
    ['NG','SUPPORT MICROFINANCE BANK','090446',null, 'payaza'],
    ['NG','TAGPAY','100023',null, 'payaza'],
    ['NG','TANGERINE MONEY','090426',null, 'payaza'],
    ['NG','TEAMAPT LIMITED','110007',null, 'payaza'],
    ['NG','TEASY MOBILE','100010',null, 'payaza'],
    ['NG','THINK FINANCE MICROFINANCE BANK','090373',null, 'payaza'],
    ['NG','TRIDENT MICROFINANCE BANK','090146',null, 'payaza'],
    ['NG','TRUST MICROFINANCE BANK','090327',null, 'payaza'],
    ['NG','CASHCONNECT MICROFINANCE BANK','090360',null, 'payaza'],
    ['NG','CBN','000028',null, 'payaza'],
    ['NG','CELLULANT','100005',null, 'payaza'],
     ['NG','CHAMS MOBILE','100015',null, 'payaza'],
    ['NG','CHANGHAN RTS MICROFINANCE BANK','090470',null, 'payaza'],
    ['NG','CHIKUM MICROFINANCE BANK','090141',null, 'payaza'],
    ['NG','CIT MICROFINANCE BANK','090144',null, 'payaza'],
    ['NG','COASTLINE MICROFINANCE BANK','090374',null, 'payaza'],
    ['NG','CONSUMER MICROFINANCE BANK','090130',null, 'payaza'],
    ['NG','COOP MORTGAGE BANK','070021',null, 'payaza'],
    ['NG','CORESTEP MICROFINANCE BANK','090365',null, 'payaza'],
    ['NG','Moremonee Microfinance Bank','090685',null, 'payaza'],
    ['NG','AB MICROFINANCE BANK','090270',null, 'payaza'],
    ['NG','ABOVE ONLY MICROFINANCE BANK','090260',null, 'payaza'],
     ['NG','ABU MICROFINANCE BANK','090197',null, 'payaza'],
    ['NG','ACCELEREX NETWORK LIMITED','90202',null, 'payaza'],
    ['NG','ACCELEREX NETWORK LIMITED','090202',null, 'payaza'],
    ['NG','ACCESS MONEY','100013',null, 'payaza'],
    ['NG','ACCESS YELLO & BETA','100052',null, 'payaza'],
    ['NG','9 PAYMENT SOLUTIONS BANK','120001','https://payaza-assets.s3.amazonaws.com/production/1714319954967-9PAYMENTSOLUTIONSBANK.png', 'payaza'],
    ['NG','ACCION MICROFINANCE BANK','090134',null, 'payaza'],
    ['NG','ADDOSSER MICROFINANCE BANK','090160',null, 'payaza'],
    ['NG','ADEYEMI COLLEGE STAFF MICROFINANCE BANK','090268',null, 'payaza'],
    ['NG','ADVANS LA FAYETTE  MICROFINANCE BANK','90155',null, 'payaza'],
    ['NG','ADVANS LA FAYETTE  MICROFINANCE BANK','090155',null, 'payaza'],
    ['NG','AFEKHAFE MICROFINANCE BANK','090292',null, 'payaza'],
    ['NG','AG MORTGAGE BANK','100028',null, 'payaza'],
    ['NG','AGOSASA MICROFINANCE BANK','090371',null, 'payaza'],
    ['NG','AL-BARAKAH MICROFINANCE BANK','090133',null, 'payaza'],
    ['NG','ALEKUN MICROFINANCE BANK','090259',null, 'payaza'],
     ['NG','ALERT MICROFINANCE BANK','090297',null, 'payaza'],
    ['NG','PROVIDUS BANK','000023','https://payaza-assets.s3.amazonaws.com/production/1718610711204-download(6).jpg', 'payaza'],
    ['NG','PREMIUM TRUST BANK','000031','https://payaza-assets.s3.amazonaws.com/production/1718610837941-pmtlogo.png', 'payaza'],
    ['NG','PAYSTACK PAYMENT LIMITED','110006','https://payaza-assets.s3.amazonaws.com/production/1718749053158-paystack.png', 'payaza'],
    ['NG','GLOBUS BANK','000027','https://payaza-assets.s3.amazonaws.com/production/1718749185059-globus.png', 'payaza'],
    ['NG','Nombank MFB','090645','', 'payaza'],
    ['NG','GOMONEY','100022',null, 'payaza'],
    ['NG','LOTUS BANK','000029','https://payaza-assets.s3.amazonaws.com/production/1721480260204-lotus.png', 'payaza'],
    ['NG','STANDARD CHARTERED BANK','000021','https://nigerianbanks.xyz/logo/standard-chartered-bank.png'],
    ['NG','Prospa Capital Microfinance Bank','090495','https://payaza-assets.s3.amazonaws.com/production/1741367609345-images.jpeg', 'payaza'],
    ['NG','GTBANK PLC','000013','https://nigerianbanks.xyz/logo/guaranty-trust-bank.png', 'payaza'],
    ['NG','Northquest Finance','050030',null, 'payaza'],
    ['NG','M36','100035',null, 'payaza'],
     ['NG','PAGA','100002','','payaza'],
    ['NG','KEYSTONE BANK','000002','https://nigerianbanks.xyz/logo/keystone-bank.png', 'payaza'],
    ['NG','BANK78 (78 Finance Company Limited)','090866',null, 'payaza'],
    ['NG','STERLING BANK','000001','https://payaza-assets.s3.amazonaws.com/production/1721506265930-sterlingbank.jpeg', 'payaza'],
    ['NG','OPAY','100004','https://payaza-assets.s3.amazonaws.com/production/1718746203958-download(7).jpg', 'payaza'],
    ['NG','BANK78 MFB / 78 FINANCE COMPANY LIMITED','110072','https://payaza-assets.s3.amazonaws.com/production/1718746304218-78finance.jpg', 'payaza'],
    ['NG','ZENITH BANK','000015','https://nigerianbanks.xyz/logo/zenith-bank.png', 'payaza'],
    ['NG','ACCESS(DIAMOND) BANK','000005','https://payaza-assets.s3.amazonaws.com/production/1714322399635-ACCESSBANK.jpeg', 'payaza'],
    ['NG','MONIEPOINT MICROFINANCE BANK','090405','https://payaza-assets.s3.amazonaws.com/production/1718747612953-monie.jpg', 'payaza'],
    ['NG','FIRST CITY MONUMENT BANK','000003','https://payaza-assets.s3.amazonaws.com/production/1718748509487-fcmb.png', 'payaza'],
    ['NG','KUDA MICROFINANCE BANK','090267','https://payaza-assets.s3.amazonaws.com/production/1718747414129-kuda.png', 'payaza'],
    ['NG','TRUSTBANC J6 MICROFINANCE BANK LIMITED','090123',null, 'payaza'],
    ['NG','TRUSTBOND MORTGAGE BANK','090005',null, 'payaza'],
    ['NG','TRUSTFUND MICROFINANCE BANK','090276',null, 'payaza'],
    ['NG','U & C MICROFINANCE BANK','090315',null, 'payaza'],
    ['NG','UNAAB MICROFINANCE BANK','090331',null, 'payaza'],
        ['NG','UNIBEN MICROFINANCE BANK','090266',null, 'payaza'],
    ['NG','UNICAL MICROFINANCE BANK','090193',null, 'payaza'],
    ['NG','UNICAL MICROFINANCE BANK','90193',null, 'payaza'],
    ['NG','UNIVERSITY OF NIGERIA, NSUKKA MICROFINANCE BANK','090251',null, 'payaza'],
    ['NG','VENTURE GARDEN NIGERIA LIMITED','110009',null, 'payaza'],
    ['NG','VIRTUE MICROFINANCE BANK','090150',null, 'payaza'],
    ['NG','BANC CORP MICROFINANCE BANK','090581',null, 'payaza'],
    ['NG','REHOBOTH MICROFINANCE BANK','090463',null, 'payaza'],
    ['NG','KKU MICROFINANCE BANK','090606',null, 'payaza'],
    ['NG','LEADREMIT LIMITED','110044',null, 'payaza'],
    ['NG','SIMPLE FINANCE LIMITED','050008',null, 'payaza'],
    ['NG','FAST CREDIT LIMITED','050009',null, 'payaza'],
    ['NG','BLUEWHALES MICROFINANCE BANK','090431',null, 'payaza'],
    ['NG','GABASAWA MICROFINANCE BANK','090582',null, 'payaza'],
    ['NG','BESTSTAR MICROFINANCE BANK','090615',null, 'payaza'],
    ['NG','IBOLO MICROFINANCE BANK','090532',null, 'payaza'],
    ['NG','TRINITY FINANCE','050014',null, 'payaza'],
    ['NG','MACROD MICROFINANCE BANK LIMITED','090603',null, 'payaza'],
        ['NG','AMEGY MICROFINANCE BANK','090629',null, 'payaza'],
    ['NG','CREDITVILLE MICROFINANCE BANK','090611',null, 'payaza'],
    ['NG','GIDAUNIYAR ALHERI MICROFINANCE BANK','090621',null, 'payaza'],
    ['NG','IYIN EKITI MICROFINANCE BANK','090620',null, 'payaza'],
    ['NG','LUKEFIELD FINANCE COMPANY LIMITED','050015',null, 'payaza'],
    ['NG','UNILORIN MICROFINANCE BANK','090341',null, 'payaza'],
    ['NG','E-FINANCE','050016',null, 'payaza'],
    ['NG','DAL MICROFINANCE BANK','090596',null, 'payaza'],
    ['NG','MADOBI MICROFINANCE BANK','090605',null, 'payaza'],
    ['NG','UZONDU MICROFINANCE BANK','090453',null, 'payaza'],
    ['NG','AKU MICROFINANCE BANK','090531',null, 'payaza'],
    ['NG','AKU MICROFINANCE BANK','944',null, 'payaza'],
    ['NG','KOKO KOPE Microfinance Bank','090617',null, 'payaza'],
    ['NG','FEDETH MICROFINANCSB','120005䛑䴀伀一',null, 'payaza'],
    ['NG','CHANELLE MICROFINANCE BANK','090397',null, 'payaza'],
        ['NG','BRIYTH-COVENANT MICROFINANCE BANK','090636',null, 'payaza'],
    ['NG','CASHBRIDGE MICROFINANCE BANK','090634',null, 'payaza'],
    ['NG','CS ADVANCE FINANCE COMPANY LIMITED','050017',null, 'payaza'],
    ['NG','GLOBAL INITIATIVE MICROFINANCE BANK','090639',null, 'payaza'],
    ['NG','NSEHE MICROFINANCE BANK','090628',null, 'payaza'],
    ['NG','OHHA MICROFINANCE BANK','090626',null, 'payaza'],
    ['NG','TOTAL TRUST MICROFINANCE BANK','090613',null, 'payaza'],
    ['NG','BABURA MICROFINANCE BANK','090625',null, 'payaza'],
    ['NG','BERACHAH MICROFINANCE BANK','090618',null, 'payaza'],
    ['NG','SOURCE MICROFINANCE BANK','090641',null, 'payaza'],
    ['NG','TANGALE MICROFINANCE BANK','090638',null, 'payaza'],
    ['NG','AWACASH MICROFINANCE BANK','090633',null, 'payaza'],
    ['NG','DIOBU MICROFINANCE BANK','090643',null, 'payaza'],
    ['NG','LETSHEGO MICROFI','090420',null, 'payaza'],
    ['NG','MABINAS MICROFINANCE BANK','090630',null, 'payaza'],
    ['NG','MINJIBIR MICROFINANCE BANK','090607',null, 'payaza'],
    ['NG','OYAN MICROFINANCE BANK','090635',null, 'payaza'],
    ['NG','UNIFUND MICROFINANCE BANK LIMITED','090637',null, 'payaza'],
    ['NG','Xpresswallet','100040',null, 'payaza'],
    ['NG','BORSTAL MICROFINANCE BANK','090454',null, 'payaza'],
    ['NG','GOMBE MICROFINANCE BANK LIMITED','090586',null, 'payaza'],
    ['NG','GREENACRES MICROFINANCE BANK LTD','090599',null, 'payaza'],
    ['NG','PROSPERITY MICROFINANCE BANK','090642',null, 'payaza'],
    ['NG','SUNTOP MICROFINANCE','090644',null, 'payaza'],
    ['NG','CINTRUST MICROFINANCE BANK','090480',null, 'payaza'],
    ['NG','ILORA MICROFINANCE BANK','090430',null, 'payaza'],
    ['NG','ABSU MICROFINANCE BANK','090640',null, 'payaza'],
    ['NG','Waya Microfinance Bank','090590',null, 'payaza'],
    ['NG','CANAAN MICROFINANCE BANK','090647',null, 'payaza'],
    ['NG','OKENGWE MICROFINANCE BANK','090646',null, 'payaza'],
        ['NG','UMUCHUKWU MICROFINANCE BANK','090652',null, 'payaza'],
    ['NG','LEADCITY MICROFINANCE BANK','090650',null, 'payaza'],
    ['NG','Bunkure Microfinance Bank','090655',null, 'payaza'],
    ['NG','NEXIM BANK','030001',null, 'payaza'],
    ['NG','ODOAKPU Microfinance Bank','090654',null, 'payaza'],
    ['NG','PYRAMID MICROFINANCE BANK','090657',null, 'payaza'],
    ['NG','VALE FINANCE LIMITED','110071',null, 'payaza'],
    ['NG','ALTERNATIVE BANK LIMITED','000037',null, 'payaza'],
    ['NG','CASHRITE MICROFINANCE BANK','090649',null, 'payaza'],
    ['NG','MICHAEL OKPARA UNIAGRIC MICROFINANCE BANK','090659',null, 'payaza'],
    ['NG','ROYAL BLUE MICROFINANCE BANK','090622',null, 'payaza'],
    ['NG','CAPSTONE MICROFINANCE BANK','090445',null, 'payaza'],
    ['NG','FORTRESS MICROFINANCE BANK','090486',null, 'payaza'],
    ['NG','MICROBIZ MICROFINANCE BANK','090587',null, 'payaza'],
    ['NG','BUNDI MICROFINANCE BANK','090661',null, 'payaza'],
    ['NG','ENTITY MICROFINANCE BANK','090656',null, 'payaza'],
    ['NG','GWONG MICROFINANCE BANK','090500',null, 'payaza'],
    ['NG','REVELATION MICROFINANCE BANK','090666',null, 'payaza'],
    ['NG','UMUCHINEMERE PROCREDIT MICROFINANCE BANK','090664',null, 'payaza'],
    ['NG','KADUPE MICROFINANCE BANK','090669',null, 'payaza'],
    ['NG','TREASURES MICROFINANCE BANK','090663',null, 'payaza'],
    ['NG','VFD MFB','090110','566', 'payaza'],
    ['GH', 'REPUBLIC BANK', 'RPB', null, 'payaza'],
    ['GH', 'BANK OF GHANA', 'BOG', null, 'payaza'],
    ['GH', 'UBA GHANA', 'UBA', null, 'payaza'],
    ['GH', 'FIDELITY BANK GHANA', 'FIB', null, 'payaza'],
    ['GH', 'Consolidated Bank Ghana', 'CBG', null, 'payaza'],
    ['GH', 'Universal Merchant Bank', 'UMB', null, 'payaza'],
    ['GH', 'APEX BANK', 'ARB', null, 'payaza'],
    ['GH', 'OMNI BANK', 'OMN', null, 'payaza'],
    ['GH', 'National Investment Bank Limited', 'NIB', null, 'payaza'],
    ['GH', 'Agricultural Development Bank GHANA', 'ADB', null, 'payaza'],
    ['GH', 'ZENITH BANK GHANA', 'ZEB', null, 'payaza'],
    ['GH', 'ZEEPAY GHANA', 'ZEE', null, 'payaza'],
    ['GH', 'STANBIC BANK GHANA', 'STB', null, 'payaza'],
    ['GH', 'STANDARD CHARTERED GHANA', 'SCB', null, 'payaza'],
    ['GH', 'MTN (MOBILE MONEY)', 'MTN', null, 'payaza'],
    ['GH', 'SERVICES INTEGRITY SAVINGS & LOANS', 'SIS', null, 'payaza'],
    ['GH', 'ABSA BANK', 'ABS', null, 'payaza'],
    ['GH', 'First Atlantic Bank', 'FAB', null, 'payaza'],
    ['GH', 'ACCESS BANK GHANA', 'ACB', null, 'payaza'],
    ['GHA', 'AIRTELTIGO MONEY', 'AIR', null, 'payaza'],
    ['GH', 'First National Bank', 'FNB', null, 'payaza'],
    ['GH', 'G-MONEY', 'GMO', null, 'payaza'],
    ['GH', 'GCB Bank Limited', 'GCB', null, 'payaza'],
    ['GHA', 'TELECEL CASH (MOBILE MONEY)', 'VOD', null, 'payaza'],
    ['GH', 'Ghl Bank Limited', 'GHL', null, 'payaza'],
    ['GH', 'Bank of Africa Ghana Limited', 'BOA', null, 'payaza'],
     ['GH', 'Prudential Bank Limited', 'PRB', null, 'payaza'],
    ['GH', 'FBNBank Ghana Limited', 'FBN', null, 'payaza'],
    ['GH', 'ECOBANK GHANA', 'ECO', null, 'payaza'],
    ['GH', 'CAL BANK', 'CAL', null, 'payaza'],
    ['GH', 'Societe Generale Ghana Limited', 'SGB', null, 'payaza'],
    ['GH', 'GT BANK GHANA', 'GTB', null, 'payaza'],
     ['KE', 'Kenya Commercial Bank', '0001', null, 'payaza'],
    ['KE', 'Standard Chartered Kenya', '0002', null, 'payaza'],
    ['KE', 'Citi Bank', '0016', null, 'payaza'],
    ['KE', 'Diamond Trust Bank', '0063', null, 'payaza'],
    ['KEN', 'AIRTEL Money Kenya', 'AIRKEN', null, 'payaza'],
    ['KE', 'ABSA Bank Kenya', '0003', null, 'payaza'],
    ['KE', 'Middle East Bank', '0018', null, 'payaza'],
    ['KE', 'Equity Bank', '0068', null, 'payaza'],
    ['KE', 'Bank of Baroda', '0006', null, 'payaza'],
    ['KE', 'Bank of Africa', '0019', null, 'payaza'],
     ['KE', 'Stanbic Bank Kenya', '0031', null, 'payaza'],
    ['KE', 'African Bank Corporation Limited', '0035', null, 'payaza'],
    ['KE', 'Ecobank Transnational Inc.', '0043', null, 'payaza'],
    ['KE', 'Caritas Microfinance Bank', '0048', null, 'payaza'],
    ['KE', 'Paramount Bank', '0050', null, 'payaza'],
    ['KE', 'Kingdom Bank Limited', '0051', null, 'payaza'],
    ['KE', 'Guaranty Trust Holding Company PLC', '0053', null, 'payaza'],
    ['KE', 'Family Bank', '0070', null, 'payaza'],
    ['KE', 'National Commercial Bank of Africa', '0007', null, 'payaza'],
    ['KE', 'Consolidated Bank Kenya', '0023', null, 'payaza'],
    ['KE', 'Housing finance Company', '0061', null, 'payaza'],
    ['KE', 'Commercial International Bank Kenya Limited', '0065', null, 'payaza'],
     ['KE', 'Gulf African Bank', '0072', null, 'payaza'],
    ['KE', 'First Community Bank', '0074', null, 'payaza'],
    ['KE', 'Dubai Islamic Bank', '0075', null, 'payaza'],
    ['KE', 'Kenya Women Microfinance Bank', '0078', null, 'payaza'],
    ['KE', 'Faulu Bank', '0079', null, 'payaza'],
    ['KE', 'Prime Bank  Limited', '0010', null, 'payaza'],
    ['KE', 'Credit Bank Limited', '0025', null, 'payaza'],
    ['KE', 'Unaitas Sacco', '0032', null, 'payaza'],
    ['KE', 'Guardian Bank Limited', '0055', null, 'payaza'],
    ['KE', 'Investments & Morgage Limited', '0057', null, 'payaza'],
    ['KE', 'Sidian Bank', '0066', null, 'payaza'],
    ['KEN', 'UBA Kenya', '0076', null, 'payaza'],
    ['KE', 'Cooperative Bank of Kenya', '0011', null, 'payaza'],
    ['KE', 'Choice Microfinance Bank Kenya Limited', '0036', null, 'payaza'],
    ['KE', 'Stima SACCO', '0089', null, 'payaza'],
    ['KE', 'National Bank of kenya', '0012', null, 'payaza'],
    ['KE', 'Victoria Commercial Bank', '0054', null, 'payaza'],
    ['KEN', 'MPESA', 'SAFKEN', null, 'payaza'],
    ['KE', 'Oriental Commercial Bank Limited', '0014', null, 'payaza'],
    ['KE', 'SBM Bank Kenya', '0060', null, 'payaza'],
    ['TZA', 'AIRTEL Money Tanzania', 'AIRTZA', null, 'payaza'],
    ['TZ', 'NATIONAL MICROFINANCE BANK LIMITED', 'NMBTZA', null, 'payaza'],
    ['TZ', 'YETU MICROFINANCE BANK PLC', 'YETTZA', null, 'payaza'],
    ['TZ', 'AMANA BANK LIMITED', 'AMATZA', null, 'payaza'],
    ['TZ', 'BANK OF TANZANIA', 'BOTTZA', null, 'payaza'],
    ['TZ', 'CRDB BANK PLC', 'CRDTZA', null, 'payaza'],
    ['TZ', 'PEOPLE’S BANK OF ZANZIBAR LTD', 'PBZTZA', null, 'payaza'],
    ['TZ', 'CITIBANK TANZANIA LTD', 'CITTZA', null, 'payaza'],
    ['TZ', 'AKIBA COMMERCIAL BANK LTD', 'AKITZA', null, 'payaza'],
     ['TZ', 'KCB BANK TANZANIA LIMITED', 'KCBTZA', null, 'payaza'],
    ['TZ', 'UCHUMI COMMERCIAL BANK  (T) LTD', 'UCHTZA', null, 'payaza'],
    ['TZ', 'CANARA BANK TANZANIA LTD', 'CANTZA', null, 'payaza'],
    ['TZA', 'Mixx By Yass', 'TIGTZA', null, 'payaza'],
    ['TZ', 'STANDARD CHARTERED BANK (T) LIMITED', 'SCBTZA', null, 'payaza'],
    ['TZ', 'EXIM BANK (TANZANIA) LTD', 'EXITZA', null, 'payaza'],
    ['TZ', 'INTERNATIONAL COMMERCIAL BANK (TANZANIA) LIMITED', 'ICBTZA', null, 'payaza'],
    ['TZ', 'GUARANTY TRUST BANK (T) LTD', 'GTBTZA', null, 'payaza'],
    ['TZ', 'BANK OF INDIA (TANZANIA) LIMITED', 'BOITZA', null, 'payaza'],
    ['TZ', 'FIRST NATIONAL BANK LIMITED', 'FIRTZA', null, 'payaza'],
    ['TZ', 'STANBIC BANK TANZANIA LTD.', 'STATZA', null, 'payaza'],
     ['TZ', 'I  M BANK LIMITED', 'IMBTZA', null, 'payaza'],
    ['TZ', 'MKOMBOZI COMMERCIAL BANK', 'MKOTZA', null, 'payaza'],
    ['TZ', 'MWALIMU COMMERCIAL BANK PLC', 'MWLTZA', null, 'payaza'],
    ['TZ', 'BANK OF AFRICA TANZANIA LIMITED', 'BOATZA', null, 'payaza'],
    ['TZ', 'DAR ES SALAAM COMMUNITY BANK LTD', 'DCBTZA', null, 'payaza'],
    ['TZ', 'UNITED BANK FOR AFRICA (T) LTD', 'UBATZA', null, 'payaza'],
    ['TZ', 'MWANGA HAKIKA MICROFINANCE BANK LIMITED', 'MWATZA', null, 'payaza'],
    ['TZ', 'MAENDELEO BANK LTD', 'MAETZA', null, 'payaza'],
    ['TZA', 'HALOPESA', 'HALTZA', null, 'payaza'],
    ['TZ', 'NATIONAL BANK OF COMMERCE LTD', 'NBCTZA', null, 'payaza'],
    ['TZ', 'HABIB AFRICAN BANK LIMITED', 'HABTZA', null, 'payaza'],
    ['TZ', 'NCBA BANK LIMITED', 'NCBTZA', null, 'payaza'],
    ['TZ', 'BANK OF BARODA (TANZANIA) LTD', 'BARTZA', null, 'payaza'],
    ['TZ', 'AZANIA BANK LIMITED', 'AZATZA', null, 'payaza'],
    ['TZ', 'ECOBANK TANZANIA LIMITED', 'ECOTZA', null, 'payaza'],
    ['TZ', 'EQUITY BANK TANZANIA LIMITED', 'EQUTZA', null, 'payaza'],
    ['TZ', 'KILIMANJARO CO-OPERATIVE BANK LTD', 'KLITZA', null, 'payaza'],
    ['TZ', 'DIAMOND TRUST BANK TANZANIA LTD', 'DTBTZA', null, 'payaza'],
    ['TZ', 'AFRICAN BANKING CORPORATION TANZANIA LIMITED', 'BANTZA', null, 'payaza'],
    ['TZ', 'ACCESSBANK TANZANIA LTD', 'ACCTZA', null, 'payaza'],
    ['TZ', 'TANZANIA COMMERCIAL BANK PLC', 'TCBTZA', null, 'payaza'],
    ['TZ', 'CHINA DASHENG BANK LIMITED', 'CHITZA', null, 'payaza'],
     ['ZAF', 'ABSA', 'ABSZAR', null, 'payaza'],
    ['ZAF', 'Ned Bank', 'NEDZAR', null, 'payaza'],
    ['ZAF', 'Capitec Personal', 'CAPZAR', null, 'payaza'],
    ['ZAF', 'ACCESS', 'ACCZAR', null, 'payaza'],
    ['ZAF', 'SASFIN', 'SASZAR', null, 'payaza'],
    ['ZAF', 'HSBC', 'HSBZAR', null, 'payaza'],
    ['ZAF', 'UBANK', 'UBAZAR', null, 'payaza'],
    ['ZAF', 'GRINDROD', 'GRIZAR', null, 'payaza'],
    ['ZAF', 'STANDARD CHARTERED', 'STAZAR', null, 'payaza'],
    ['ZAF', 'INVESTEC', 'INVZAR', null, 'payaza'],
    ['ZAF', 'FIRST RAND', 'FIRZAR', null, 'payaza'],
    ['ZAF', 'FNB', 'FNBZAR', null, 'payaza'],
    ['ZAF', 'Capitec Business', 'CPZZAR', null, 'payaza'],
    ['ZAF', 'Tyme Bank', 'TYMZAR', null, 'payaza'],
    ['ZAF', 'WINDHOEK', 'WINZAR', null, 'payaza'],
    ['ZAF', 'IMPERIAL', 'IMPZAR', null, 'payaza'],
    ['ZAF', 'STANDARD', 'STNZAR', null, 'payaza'],
    ['ZAF', 'Bidvest', 'BIDZAR', null, 'payaza'],
    ['ZAF', 'Discovery Bank', 'DISZAR', null, 'payaza'],
    ['ZAF', 'AFRIBANK', 'AFRZAR', null, 'payaza'],
    ['ZAF', 'OLD MUTUAL', 'OLDZAR', null, 'payaza'],

     ['GHA', 'REPUBLIC BANK', 'RPB', null, 'app$mobile'],
    ['GHA', 'ADB', 'ADB', null, 'app$mobile'],
    ['GHA', 'VODAFONE CASH', 'VOD', null, 'app$mobile'],
    ['GHA', 'ZEEPAY GHANA', 'ZEE', null, 'app$mobile'],
    ['GHA', 'ABSA BANK', 'ABS', null, 'app$mobile'],
    ['GHA', 'FNB', 'FNB', null, 'app$mobile'],
    ['GHA', 'CBG', 'CBG', null, 'app$mobile'],
    ['GHA', 'GHL BANK', 'GHL', null, 'app$mobile'],
    ['GHA', 'AIRTELTIGO MONEY', 'AIR', null, 'app$mobile'],
    ['GHA', 'UMB', 'UMB', null, 'app$mobile'],
    ['GHA', 'SERVICES INTEGRITY SAVINGS & LOANS', 'SIS', null, 'app$mobile'],
    ['GHA', 'FBN BANK', 'FBN', null, 'app$mobile'],
    ['GHA', 'UBA', 'UBA', null, 'app$mobile'],
    ['GHA', 'CAL BANK', 'CAL', null, 'app$mobile'],
    ['GHA', 'SG', 'SGB', null, 'app$mobile'],
    ['GHA', 'APEX BANK', 'ARB', null, 'app$mobile'],
    ['GHA', 'BANK OF GHANA', 'BOG', null, 'app$mobile'],
    ['GHA', 'OMNI BANK', 'OMN', null, 'app$mobile'],
    ['GHA', 'STANBIC BANK', 'STB', null, 'app$mobile'],
    ['GHA', 'FAB', 'FAB', null, 'app$mobile'],
    ['GHA', 'NIB', 'NIB', null, 'app$mobile'],
    ['GHA', 'G-MONEY', 'GMO', null, 'app$mobile'],
    ['GHA', 'BOA', 'BOA', null, 'app$mobile'],
    ['GHA', 'ECOBANK GHANA', 'ECO', null, 'app$mobile'],
    ['GHA', 'GT BANK', 'GTB', null, 'app$mobile'],
    ['GHA', 'MTN MOBILE MONEY', 'MTN', null, 'app$mobile'],
    ['GHA', 'FIDELITY BANK', 'FIB', null, 'app$mobile'],
    ['GHA', 'ZENITH BANK', 'ZEB', null, 'app$mobile'],
    ['GHA', 'STANDARD CHARTERED', 'SCB', null, 'app$mobile'],
    ['GHA', 'PBL', 'PRB', null, 'app$mobile'],
    ['GHA', 'ACCESS BANK', 'ACB', null, 'app$mobile'],
    ['GHA', 'GCB BANK', 'GCB', null, 'app$mobile'],


    ];
     foreach ($banks as $bank) {
                    Bank::updateOrCreate(
                [
                    'country_iso' => $bank[0],
                    'bank_code' => $bank[2],
                    'provider' => $bank[4] ?? 'payaza', // use default if key 4 doesn't exist
                ],
                [
                    'name' => $bank[1],
                    'sort_code' => $bank[3] ?? null,     // default null if key 3 doesn't exist
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

}
}
